spring:
  application:
    name: platform-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/fastship}
    username: ${DB_USERNAME:fastship}
    password: ${DB_PASSWORD:fastship}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
